[package]
name = "lumen-provider-json"
version = "0.1.0"
edition = "2021"

[dependencies]
lumen-runtime = { path = "../lumen-runtime" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
